CoblentzNumbers/urls.py
from django.urls import path
from CoblentzNumbers import views

app_name = 'CoblentzNumbers'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:shift_id>/', views.shift_detail, name='shift_detail'),
    path('create/', views.create_shift, name='create_shift'),
    path('current/', views.all_shifts, name='all_shifts'),
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('', views.home, name='home'),
    path('login/', views.loginuser, name='loginuser'),
]

blog/urls.py
from django.urls import path
from portfolio.static import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail')
   ]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('CoblentzNumbers/', include('CoblentzNumbers.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoblentzNumbers/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import date, datetime, time, timedelta
from django.contrib.auth.models import User

# Create your models here.
class CoblentzNumbers(models.Model):
    date = models.DateField(auto_now_add=False)
    class AMorPM(models.TextChoices):
        AM = 'AM', _('AM')
        PM = 'PM', _('PM')

    shift = models.CharField(max_length=2, choices=AMorPM.choices, default=AMorPM.AM)
    numbers = models.CharField(max_length=200) #For now, sadly, a comma delimited list of shift numbers
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=3)

    class Meta:
        unique_together = ('date', 'shift',)

    def __str__(self):
        return str(self.date) + ' ' + str(self.shift) + ' User: ' + str(self.user)

    def counts_and_averages(self):
        times_and_numbers = {}
        initial_time = 10 if self.shift == self.AMorPM.AM else 16
        minute_start = 0
        if initial_time == 10:
            minute_start = 15
        else:
            minute_start = 45
        myTime = datetime(year=2021,month=7,day=1,hour=initial_time, minute=minute_start, second=0)
        count = 1
        last_number = 0
        last_number_index = -1
        index = 1
        for number in self.numbers.split(','):
            if RepresentsInt(number):
                last_number_index = index
            index += 1
        for number in self.numbers.split(','):
            try:
                print(f"In try, number is {number}, count is {count}")
                running_average = int(number) / int(count)
                number_in_last_15 = int(number) - last_number
                last_number = int(number)
                print(f"running_average is {running_average}")
            except:
                print(f"Caused an exception")
                running_average = last_number / int(count)
                number_in_last_15 = 0
            if count > last_number_index:
                number_in_last_15 = ''
                running_average = ''
            if running_average != '':
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, "{:.2f}".format(running_average)]
            else:
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, running_average]
            #print('OUR COUNT IS: ' + str(count) + ' and LAST_NUMBER_INDEX IS: ' + str(last_number_index))

            #print(f"OUR TOTAL ARRAY: {times_and_numbers}")
            myTime += timedelta(minutes=15)
            count += 1
        print(times_and_numbers)
        return times_and_numbers

    def counts_and_averages_First(self):
        times_and_numbers = {}
        initial_time = 10 if self.shift == self.AMorPM.AM else 16
        minute_start = 0
        if initial_time == 10:
            minute_start = 15
        else:
            minute_start = 45
        myTime = datetime(year=2021,month=7,day=1,hour=initial_time, minute=minute_start, second=0)
        count = 1
        last_number = 0
        last_number_index = -1
        index = 1
        limiting_index = 0
        for number in self.numbers.split(','):
            if RepresentsInt(number):
                last_number_index = index
            index += 1
        for number in self.numbers.split(','):
            try:
                print(f"In try, number is {number}, count is {count}")
                running_average = int(number) / int(count)
                number_in_last_15 = int(number) - last_number
                last_number = int(number)
                print(f"running_average is {running_average}")
            except:
                print(f"Caused an exception")
                running_average = last_number / int(count)
                number_in_last_15 = 0
            if count > last_number_index:
                number_in_last_15 = ''
                running_average = ''
            if running_average != '':
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, "{:.2f}".format(running_average)]
            else:
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, running_average]
            #print('OUR COUNT IS: ' + str(count) + ' and LAST_NUMBER_INDEX IS: ' + str(last_number_index))

            #print(f"OUR TOTAL ARRAY: {times_and_numbers}")
            myTime += timedelta(minutes=15)
            count += 1
            limiting_index += 1
            if limiting_index == 4:
                break
        print(times_and_numbers)
        return times_and_numbers

    def counts_and_averages_Second(self):
        times_and_numbers = {}
        initial_time = 10 if self.shift == self.AMorPM.AM else 16
        minute_start = 0
        if initial_time == 10:
            initial_time = 11
            minute_start = 15
        else:
            minute_start = 45
        myTime = datetime(year=2021,month=7,day=1,hour=initial_time, minute=minute_start, second=0)
        count = 1
        last_number = 0
        last_number_index = -1
        index = 1
        limiting_index = 0
        row = 5
        for number in self.numbers.split(','):
            if RepresentsInt(number):
                last_number_index = index
            index += 1
        if last_number_index < 5:
            last_number_index = -1
        else:
            last_number_index -= 4
        print(f"Last number index is {last_number_index}")
        print(f"The number list is {self.numbers.split(',')}")
        print(f"Times and numbers: {times_and_numbers}")
        for number in self.numbers.split(','):
            limiting_index += 1
            if limiting_index < 5:
                continue
            try:
                print(f"In try, number is {number}, count is {count}")
                running_average = int(number) / int(count)
                number_in_last_15 = int(number) - last_number
                last_number = int(number)
                print(f"running_average is {running_average}")
            except:
                print(f"Caused an exception")
                running_average = last_number / int(count)
                number_in_last_15 = 0
            if count > last_number_index:
                number_in_last_15 = ''
                running_average = ''
            if running_average != '':
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, "{:.2f}".format(running_average), f"table_{row}"]
            else:
                times_and_numbers[myTime.strftime("%H:%M")] = [number, number_in_last_15, running_average, f"table_{row}"]
            #print('OUR COUNT IS: ' + str(count) + ' and LAST_NUMBER_INDEX IS: ' + str(last_number_index))

            #print(f"OUR TOTAL ARRAY: {times_and_numbers}")
            myTime += timedelta(minutes=15)
            count += 1
            row += 1
        print(f"Times and numbers before return: {times_and_numbers}")
        return times_and_numbers

    def DayOfWeek(self):
        print("The DATE is: " + str(self.date))
        return self.date.strftime("%A")

def RepresentsInt(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

CoblentzNumbers/forms.py
from django.forms import ModelForm
from .models import CoblentzNumbers

class ShiftForm(ModelForm):
    class Meta:
        model = CoblentzNumbers
        fields = ['date', 'shift']

class ShiftDetailForm(ModelForm):
    class Meta:
        model = CoblentzNumbers
        fields = ['shift', 'date', 'numbers']

CoblentzNumbers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from CoblentzNumbers.models import CoblentzNumbers
from datetime import date
from .forms import ShiftForm, ShiftDetailForm
from .models import CoblentzNumbers
from datetime import date, datetime, time, timedelta
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required

@login_required
def all_shifts(request):
    #shift_count = CoblentzNumbers.objects.count()
    #rint(str(shift_count) + " is the number of shift objects")
    #shifts = CoblentzNumbers.objects.order_by('-date')[:10]
    shifts = CoblentzNumbers.objects.filter(user=request.user).order_by('-date')
    #print(str(shifts))
    #first_date = shifts[0].date
    #print(first_date)
    #second_date = shifts[1].date
    #print(second_date)
    random_text = 'Random Text'
    return render(request, 'CoblentzNumbers/all_shifts.html',
                  {'shifts': shifts})

@login_required
def shift_detail(request, shift_id):
    shift = get_object_or_404(CoblentzNumbers, pk=shift_id)
    if request.method == 'GET':
        form = ShiftForm(instance=shift)
        return render(request, 'CoblentzNumbers/detail.html', {'shift': shift, 'form': form})
    else:
        try:
            form = ShiftDetailForm(request.POST, instance=shift)
            #print(f"The form itself: {str(form.shift)}")
            form_date = request.POST.get('date')
            #print(f"The date retrieved from the form is {form_date}")
            if form.is_valid():
                form_numbers = request.POST.get('numbers')
                #print(f"The form numbers are: {form_numbers}")
                form.save()
                return render(request,  'CoblentzNumbers/detail.html', {'shift': shift, 'form': form, 'success': 'Saved'})
            else:
                #print('form error is: ' + str(form.errors))
                return render(request, 'CoblentzNumbers/detail.html', {'form': form})
        except ValueError as e:
            return render(request, 'CoblentzNumbers/detail.html', {'form': ShiftDetailForm(), 'error': f'Bad Data - {e}',})

def valid_numbers(numbers):
    # ensure that:
    # 1. every value is a number and/or whitespace, and not counted in the next thing
    # 2. all the *numbers* are strictly ascending (more important that the first point)
    highestNumber = 0
    currentLine = 1
    returnValue = 'Good'
    numberList = numbers.split(",")
    for number in numberList:
        if number.isspace()  or len(number) == 0:
            currentLine += 1
            continue
        elif number.isnumeric():
            if int(number) >= highestNumber:
                highestNumber = int(number)
            else:
                #print(f"***highest number is {highestNumber}, current number is {number}, current line is {currentLine}")
                returnValue = 'Numbers must never be descending! Check line ' + str(currentLine)
                break
        else:
            returnValue = 'No non-numeric values allowed! Check line ' + str(currentLine)
        currentLine += 1
    return returnValue

#def create_shift(request):
#    today = date.today()
#    print(today)
#    return render(request, 'CoblentzNumbers/create.html', {'myToday': today})

@login_required
def create_shift(request):
    if request.method == "GET":
        return render(request, 'CoblentzNumbers/create.html', {'form': ShiftForm()})
    else:
        try:
            #print('CREATING NEW SHIFT')
            form = ShiftForm(request.POST)
            #print('WE HAVE THE FORM')
            newShift = form.save(commit=False)
            #print('WE HAVE THE NEW SHIFT')
            #print(str(newShift))
            #print(request.user)
            newShift.user = request.user
            #print('request.user = ' + str(newShift.user))
            #print(f"Day of week: {newShift.date.weekday()}")
            #print(f"newShift.date is {newShift.date.weekday()}")
            #print(f"Shift is {newShift.shift}")
            if newShift.date.weekday() < 4 or newShift.shift == 'AM':
                newShift.numbers = " , , , , , , , , , , , , , "
            else:
                newShift.numbers = " , , , , , , , , , , , "
            newShift.save()
            return redirect('CoblentzNumbers:shift_detail', newShift.id)
        except ValueError as error:
            #print(error)
            return render(request, 'CoblentzNumbers/create.html', {'form': ShiftForm(), 'error': 'This shift already exists'})

def signupuser(request):
    if request.method == "GET":
        return render(request, 'CoblentzNumbers/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('CoblentzNumbers:all_shifts')
            except:
                return render(request, 'CoblentzNumbers/signupuser.html', {'form': UserCreationForm(), 'error': 'Username already in use - choose another'})
        else:
            #print("The passwords don't match")
            return render(request, 'CoblentzNumbers/signupuser.html', {'form': UserCreationForm(), 'error': 'Passwords do not match'})

@login_required
def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('CoblentzNumbers:home')

def home(request):
    if request.user.is_authenticated:
        return redirect('CoblentzNumbers:all_shifts')
    else:
        return render(request, 'CoblentzNumbers/home.html')

def loginuser(request):
    if request.method == "GET":
        return render(request, 'CoblentzNumbers/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            #print('user is none')
            return render(request, 'CoblentzNumbers/loginuser.html', {'form': AuthenticationForm(), 'error': 'Username and password did not match'})
        else:
            #print('user is someone')
            login(request, user)
            #print('login was successful?')
            return redirect('CoblentzNumbers:all_shifts')

CoblentzNumbers/templates/CoblentzNumbers/all_shifts.html
{% extends "CoblentzNumbers/coblentz_base.html" %}

{% load static %}

{% block content %}

<h1 id="coblentzshifts" class="font-weight-bold text-center">{{ user.username }}'s Shifts</h1>

<h3 class="text-center mb-5">{{ user.username }} has worked {{ shifts.count }} shift{{ shifts.count|pluralize }}</h3>

<br>
<ul>
{% for shift in shifts %}
    <li>
        <a href="{% url 'CoblentzNumbers:shift_detail' shift.id %}">
            <h2>{{ shift.DayOfWeek }}, {{ shift.date }} {{ shift.shift }}</h2>
        </a>
    </li>

{% endfor %}
</ul>
<br>
<a class="btn btn-primary" href="{% url 'CoblentzNumbers:create_shift' %}">Create a New Shift</a>





{% endblock %}

CoblentzNumbers/templates/CoblentzNumbers/coblentz_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "CoblentzNumbers/Coblentz.css" %}">

    <title>Coblentz Dining Hall - Shift Numbers</title>
</head>
<body>

<ul class="navbar-nav ml-auto  list-group-horizontal">
    {% if user.is_authenticated %}
    <li class="nav-item navbar-lightblue">
        <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
        <form style='display: none;' method="POST" action="{% url 'CoblentzNumbers:logoutuser' %}">
            {% csrf_token %}
            <button id="signOutBtn" type="submit">Logout</button>
        </form>
    </li>
    {% else %}
    <li class="nav-item navbarmargin navbar-lightblue">
        <a class="nav-link" href="{% url 'CoblentzNumbers:signupuser' %}">Sign Up</a>
    </li>
    <li class="nav-item navbarmargin navbar-lightblue">
        <a class="nav-link" href="{% url 'CoblentzNumbers:loginuser' %}">Login</a>
    </li>
    {% endif %}
</ul>
<nav class="navbar">
    <div class="container CoblentzHeader" style="justify-content: center">
        <img src="{% static "portfolio/Hood.png" %}" width="80" height="80" class="d-inline-block align-top right-margin">

    </div>
</nav>
<br>
<div style="justify-content: center">
    <p class="center">Coblentz Dining Hall</p>
    <p class="center">Shift Numbers</p>
</div>
<div>

</div>
<br>
<div class="container">
    {% block content %}{% endblock %}
</div>
<br>
<br>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

CoblentzNumbers/templates/CoblentzNumbers/create.html
{% extends "CoblentzNumbers/coblentz_base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2 id="coblentzshifts" class="font-weight-bold text-center">Create New Shift</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="date">Select Date</label>
                <input type="date" name="date" value = "{{ myToday }}" class="form-control" id="date" required>
            </div>
            <div class="form-group">
                <label for="shift">Shift</label>
                <select name="shift" id="cars">
                    <option value="AM">AM</option>
                    <option value="PM">PM</option>
                </select>
            </div>
            <div class="form-group">
                <!--<input type="hidden" name="numbers" value=" , , , , , , , , , , , , , " id=""numbers required>-->
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

CoblentzNumbers/templates/CoblentzNumbers/detail.html
{% extends "CoblentzNumbers/coblentz_base.html" %}

{% load static %}

{% block content %}
<a class="btn btn-primary" href="{% url 'CoblentzNumbers:all_shifts' %}">Return to Shifts</a>
<h1 class="text-center mt-5" id="shiftdetaildate">{{ shift.DayOfWeek }}, {{ shift.date }} {{ shift.shift }}</h1>

<!--<h5 class="text-center text-muted mb-5">{{ shift.date|date:'F jS Y' }}</h5>-->
<br>
{% if error %}
<div class="alert alert-danger" role="alert">
   {{ error }}
</div>
{% endif %}
{% if success %}
<div class="alert alert-success" role="alert" id="clientsuccess">
    {{ success }}
</div>
{% endif %}
<div class="alert alert-danger" role="alert" id="clienterror" style="display: none">

</div>
{% if shift.shift == "PM" %}
Dinner
<table id="myTable" class="table">
    <colgroup>
        <col span="1" style="width: 33%;">
        <col span="1" style="width: 45%;">
        <col span="1" style="width: 22%;">
    </colgroup>
    <tr>
        <th style="text-align:left">Time</th>
        <th style="text-align:left"><div style="padding-left:75px">Count</div></th>
        <th style="text-align:left"><div># in last 15</div></th>
        <th style="text-align:left">Running Average</th>
    </tr>
    {% for key, value in shift.counts_and_averages.items %}
    <tr>
        <td>{{ key }}</td>
        <td><input id="table_{{forloop.counter}}" type="text" value="{{ value.0 }}" onkeydown="textboxFocus(this.id)";"></td>
        <td class="calculated">{{ value.1 }}</td>
        <td class="calculated">{{ value.2 }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
Continental
<table id="myTableFirst" class="table">
    <colgroup>
        <col span="1" style="width: 33%;">
        <col span="1" style="width: 45%;">
        <col span="1" style="width: 22%;">
    </colgroup>
    <tr>
        <th style="text-align:left">Time</th>
        <th style="text-align:left"><div style="padding-left:75px">Count</div></th>
        <th style="text-align:left"><div># in last 15</div></th>
        <th style="text-align:left">Running Average</th>
    </tr>
    {% for key, value in shift.counts_and_averages_First.items %}
    <tr>
        <td>{{ key }}</td>
        <td><input id="table_{{forloop.counter}}" type="text" value="{{ value.0 }}" onkeydown="textboxFocus(this.id)";"></td>
        <td class="calculated">{{ value.1 }}</td>
        <td class="calculated">{{ value.2 }}</td>
    </tr>
    {% endfor %}
</table>
Brunch
<table id="myTableSecond" class="table">
    <colgroup>
        <col span="1" style="width: 33%;">
        <col span="1" style="width: 45%;">
        <col span="1" style="width: 22%;">
    </colgroup>
    <tr>
        <th style="text-align:left">Time</th>
        <th style="text-align:left"><div style="padding-left:75px">Count</div></th>
        <th style="text-align:left"><div># in last 15</div></th>
        <th style="text-align:left">Running Average</th>
    </tr>
    {% for key, value in shift.counts_and_averages_Second.items %}
    <tr>
        <td>{{ key }}</td>
        <td><input id="{{ value.3  }}" type="text" value="{{ value.0 }}" onkeydown="textboxFocus(this.id)";"></td>
        <td class="calculated">{{ value.1 }}</td>
        <td class="calculated">{{ value.2 }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
<form id="theForm" method="POST" onsubmit="return submitFunction()">
    {% csrf_token %}
    <div class="form-group">
        <label for="memo"></label>
        <input id="AMorPM" type="hidden" name="shift" value = "{{ shift.shift }}" class="form-control" id="shift">
        <input type="hidden" name="date" value = "{{ shift.date|date:"Y-m-d" }}" class="form-control" id="date">
        <input type="hidden" name="numbers" value = "2,4,6,8" }}" class="form-control" id="numbers">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>

<script>
   window.onload = function() {
            document.getElementById('theForm').onsubmit = function() {
            var numbers = document.getElementById('numbers');
            numbers.value = "1,1,2,3,5,6,7,8,9,10,20,30,40,55";
            var myOutput = "";
            var table;
            if (document.getElementById("AMorPM").value == "PM")
            {
                table = document.getElementById("myTable");
                var rows = table.getElementsByTagName("tr");
                for (var i = 1; i <= rows.length - 1; i++)
                {
                    var cellValue = document.getElementById("table_"+i).value;
                    myOutput += cellValue.trim();
                    if (i != rows.length - 1)
                    {
                        myOutput += ",";
                    }
                }
                numbers.value = myOutput;
                document.getElementById("clienterror").style.display = "block"
                result = valid_numbers(myOutput);
                if (result != "Good")
                {
                    document.body.scrollTop = document.documentElement.scrollTop = 0;
                    return false;
                }
                else
                {
                    return true;
                }
            }
            else
            {
                table = document.getElementById("myTableFirst");
                var rows = table.getElementsByTagName("tr");
                for (var i = 1; i <= rows.length - 1; i++)
                {
                    var cellValue = document.getElementById("table_"+i).value;
                    myOutput += cellValue.trim();
                    myOutput += ",";
                }
                table = document.getElementById("myTableSecond");
                var rows = table.getElementsByTagName("tr");
                for (var i = 1; i <= rows.length - 1; i++)
                {
                    var cellValue = document.getElementById("table_"+ (i + 4)).value;
                    myOutput += cellValue.trim();
                    if (i != rows.length - 1)
                    {
                        myOutput += ",";
                    }
                }
                numbers.value = myOutput;
                //alert(myOutput);
                document.getElementById("clienterror").style.display = "block"
                result = valid_numbers(myOutput);
                if (result != "Good")
                {
                    document.body.scrollTop = document.documentElement.scrollTop = 0;
                    return false;
                }
                else
                {
                    return true;
                }
            }

        }
   }

   function custNumber(object) {
    // `this` refers to the DOM element
    alert("The object is!!!");
   }

   function textboxFocus(x)
   {
       document.getElementById(x).style.color = "#00CC00";
   }

   function valid_numbers(numbers)
   {
        //alert("validating numbers!");
        // ensure that:
        // 1. every value is a number and/or whitespace, and not counted in the next thing
        // 2. all the *numbers* are strictly ascending (more important that the first point)
        var highestNumber = 0;
        var currentLine = 1;
        var returnValue = 'Good';
        var numberList = numbers.split(",");
        //alert("Length of numberList is " + numberList.length);
        //alert("The numberList is " + numberList);
        //alert("numberList[0] is " + numberList[0]);
        //alert("numberList[1] is " + numberList[1]);
        //alert("numberList[2] is " + numberList[2]);
        //alert("numberList[3] is " + numberList[3]);
        for (var i = 0; i < numberList.length; i++)
        {
            var numberToValidate = numberList[i];
            if (isWhitespaceOrEmpty(numberToValidate) || numberToValidate.length == 0)
            {
                currentLine += 1;
                continue;
            }
            else if (isNumeric(numberToValidate))
            {
                //alert("number is ");
                if (parseInt(numberToValidate) >= highestNumber)
                {
                    highestNumber = parseInt(numberToValidate);
                }
                else
                {
                    // Numbers always ascending, except if this is the fifth element of an AM shift
                    if (!(document.getElementById("AMorPM").value == "AM" && i == 4))
                    {
                        //print(f"***highest number is {highestNumber}, current number is {number}, current line is {currentLine}");
                        returnValue = 'Numbers must never be descending! Check line ' + String(currentLine);
                        document.getElementById("clienterror").innerHTML = 'Numbers must never be descending! Check line ' + String(currentLine);
                        EmptyNumbersAndAverages(currentLine, numberList.length);
                        try
                        {
                            document.getElementById("clientsuccess").style.display = "none";
                        }
                        catch (error)
                        {
                            console.log(error);
                        }
                        document.getElementById("table_" + String(currentLine)).style.color = "#FF0000";
                        break;
                    }
                    else
                    {
                        highestNumber = parseInt(numberToValidate);
                    }
                }
            }
            else
            {
                returnValue = 'No non-numeric values allowed! Check line ' + String(currentLine);
                document.getElementById("clienterror").innerHTML = 'No non-numeric values allowed! Check line ' + String(currentLine);
                EmptyNumbersAndAverages(currentLine, numberList.length);
                try
                {
                    document.getElementById("clientsuccess").style.display = "none";
                }
                catch (error)
                {
                    console.log(error);
                }
                document.getElementById("table_" + String(currentLine)).style.color = "#FF0000";
                break;
            }
            currentLine += 1;
        }
        return returnValue;
    }

    function isNumeric(str)
    {
        if (typeof str != "string") return false // we only process strings!
        return !isNaN(str) && // use type coercion to parse the _entirety_ of the string (`parseFloat` alone does not do this)...
             !isNaN(parseFloat(str)) // ...and ensure strings of whitespace fail
    }

    function isWhitespaceOrEmpty(text)
    {
        return !/[^\s]/.test(text);
    }

    function EmptyNumbersAndAverages(line, length)
    {
        // kludgey, but, whatever, this is ver 1.0
        if (document.getElementById("AMorPM").value == "AM" && line >= 5)
        {
            line++;
        }
        var tableRows = document.getElementsByTagName("tr");

        for (var i = line; i < tableRows.length; i++)
        {
            if (document.getElementById("AMorPM").value == "AM" && i == 5)
            {
                continue;
            }
            let children = tableRows[i].children;
            for (var j = 2; j < children.length; j++)
            {
                children[j].innerHTML = "";
            }
        }
    }
</script>

{% endblock %}

CoblentzNumbers/templates/CoblentzNumbers/home.html
{% extends "CoblentzNumbers/coblentz_base.html" %}

{% block content %}
<div class="container" style="justify-content: center">
<div>Welcome! Please log in or sign up to continue!</div>
</div>
{% endblock %}